-- MySQL Script generated by MySQL Workbench
-- Thu Nov 27 22:20:58 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ezSvrMon
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ezSvrMon` ;

-- -----------------------------------------------------
-- Schema ezSvrMon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ezSvrMon` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ezSvrMon` ;

-- -----------------------------------------------------
-- Table `ezSvrMon`.`System`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezSvrMon`.`System` ;

CREATE TABLE IF NOT EXISTS `ezSvrMon`.`System` (
  `SystemID` INT NOT NULL AUTO_INCREMENT,
  `Hostname` VARCHAR(253) NULL,
  `OS` VARCHAR(45) NULL,
  `Kernel` VARCHAR(45) NULL,
  `Uptime` VARCHAR(45) NULL,
  `LastBoot` VARCHAR(20) NULL,
  `CurrentUsers` INT NULL,
  `LastChanged` DATETIME NULL,
  PRIMARY KEY (`SystemID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezSvrMon`.`RAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezSvrMon`.`RAM` ;

CREATE TABLE IF NOT EXISTS `ezSvrMon`.`RAM` (
  `System_SystemID` INT NOT NULL,
  `TotalRAM` INT NULL,
  `FreeRAM` INT NULL,
  `Timestamp` DATETIME NOT NULL,
  INDEX `fk_RAM_System_idx` (`System_SystemID` ASC),
  PRIMARY KEY (`System_SystemID`),
  CONSTRAINT `fk_RAM_System`
    FOREIGN KEY (`System_SystemID`)
    REFERENCES `ezSvrMon`.`System` (`SystemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezSvrMon`.`CPU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezSvrMon`.`CPU` ;

CREATE TABLE IF NOT EXISTS `ezSvrMon`.`CPU` (
  `System_SystemID` INT NOT NULL,
  `Model` VARCHAR(45) NULL,
  `Frequency` VARCHAR(9) NULL,
  `Cache` VARCHAR(5) NULL,
  `BogoMips` VARCHAR(8) NULL,
  `Timestamp` DATETIME NULL,
  INDEX `fk_CPU_System1_idx` (`System_SystemID` ASC),
  PRIMARY KEY (`System_SystemID`),
  CONSTRAINT `fk_CPU_System1`
    FOREIGN KEY (`System_SystemID`)
    REFERENCES `ezSvrMon`.`System` (`SystemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezSvrMon`.`Ping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezSvrMon`.`Ping` ;

CREATE TABLE IF NOT EXISTS `ezSvrMon`.`Ping` (
  `System_SystemID` INT NOT NULL,
  `Host` VARCHAR(253) NULL,
  `RTT` VARCHAR(10) NULL,
  `Timestamp` DATETIME NULL,
  PRIMARY KEY (`System_SystemID`),
  CONSTRAINT `fk_Ping_System1`
    FOREIGN KEY (`System_SystemID`)
    REFERENCES `ezSvrMon`.`System` (`SystemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezSvrMon`.`Diskspace`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezSvrMon`.`Diskspace` ;

CREATE TABLE IF NOT EXISTS `ezSvrMon`.`Diskspace` (
  `System_SystemID` INT NOT NULL,
  `FileSystem` VARCHAR(45) NULL,
  `FileSystemStatus` VARCHAR(45) NULL,
  `Timestamp` DATETIME NULL,
  PRIMARY KEY (`System_SystemID`),
  CONSTRAINT `fk_Diskspace_System1`
    FOREIGN KEY (`System_SystemID`)
    REFERENCES `ezSvrMon`.`System` (`SystemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezSvrMon`.`NetworkInterfaces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezSvrMon`.`NetworkInterfaces` ;

CREATE TABLE IF NOT EXISTS `ezSvrMon`.`NetworkInterfaces` (
  `System_SystemID` INT NOT NULL,
  `InterfaceName` VARCHAR(10) NULL,
  `InterfaceIP` INT NULL,
  `Timestamp` DATETIME NULL,
  PRIMARY KEY (`System_SystemID`),
  CONSTRAINT `fk_NetworkInterfaces_System1`
    FOREIGN KEY (`System_SystemID`)
    REFERENCES `ezSvrMon`.`System` (`SystemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezSvrMon`.`LoadAverage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezSvrMon`.`LoadAverage` ;

CREATE TABLE IF NOT EXISTS `ezSvrMon`.`LoadAverage` (
  `System_SystemID` INT NOT NULL,
  `OneMinute` VARCHAR(12) NULL,
  `FiveMinutes` VARCHAR(12) NULL,
  `FifteenMinutes` VARCHAR(12) NULL,
  `Processes` VARCHAR(45) NULL,
  `Timestamp` DATETIME NULL,
  PRIMARY KEY (`System_SystemID`),
  CONSTRAINT `fk_LoadAverage_System1`
    FOREIGN KEY (`System_SystemID`)
    REFERENCES `ezSvrMon`.`System` (`SystemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezSvrMon`.`SystemTemperature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezSvrMon`.`SystemTemperature` ;

CREATE TABLE IF NOT EXISTS `ezSvrMon`.`SystemTemperature` (
  `System_SystemID` INT NOT NULL,
  `SensorName` VARCHAR(45) NULL,
  `SensorTemperature` VARCHAR(45) NULL,
  `Timestamp` DATETIME NULL,
  PRIMARY KEY (`System_SystemID`),
  CONSTRAINT `fk_SystemTemperature_System1`
    FOREIGN KEY (`System_SystemID`)
    REFERENCES `ezSvrMon`.`System` (`SystemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezSvrMon`.`DiskTemperature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezSvrMon`.`DiskTemperature` ;

CREATE TABLE IF NOT EXISTS `ezSvrMon`.`DiskTemperature` (
  `System_SystemID` INT NOT NULL,
  `DiskName` VARCHAR(45) NULL,
  `DiskTemperature` VARCHAR(45) NULL,
  `Timestamp` VARCHAR(45) NULL,
  PRIMARY KEY (`System_SystemID`),
  CONSTRAINT `fk_DiskTemperature_System1`
    FOREIGN KEY (`System_SystemID`)
    REFERENCES `ezSvrMon`.`System` (`SystemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ezSvrMon`.`Services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ezSvrMon`.`Services` ;

CREATE TABLE IF NOT EXISTS `ezSvrMon`.`Services` (
  `System_SystemID` INT NOT NULL,
  `ServiceName` VARCHAR(45) NULL,
  `ServiceHost` VARCHAR(253) NULL,
  `ServicePort` INT NULL,
  `ServiceStatus` TINYINT(1) NULL,
  PRIMARY KEY (`System_SystemID`),
  CONSTRAINT `fk_Services_System1`
    FOREIGN KEY (`System_SystemID`)
    REFERENCES `ezSvrMon`.`System` (`SystemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO ezsmdb;
 DROP USER ezsmdb;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'ezsmdb' IDENTIFIED BY 'Welcome123';

GRANT SELECT, INSERT, TRIGGER ON TABLE `ezSvrMon`.* TO 'ezsmdb';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
